Repository clay/clay-kiln, pull requests merged in 2019-07, with the labels that each got.

#1407 Adds new component to show a sort by date dropdown
  lib/nav/page-list.vue
  lib/nav/sort-selector.vue
Labels: feature

#1465 Update kilnjs content style
  docs/kilnjs.md
Labels: docs

#1466 docs: Adding PRELOAD_SUCCESS event in kiljs documentation
  docs/kilnjs.md
Labels: docs

#1467 feat: Add UiPopover and UiConfirm to components list
  lib/utils/api.js
Labels: feature

#1468 8.12.0
  package-lock.json
  package.json
Labels: public release

#1469 Add the 'args' property and update the 'use' property to the action on the main.workflow file
  .github/main.workflow
Labels: blocked, docs

#1470 Add the install action for the doc's module
  .github/main.workflow
Labels: blocked, docs
